# Generated by Django 5.1.2 on 2024-10-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books_app", "0002_alter_livre_editeur"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auteur",
            options={
                "permissions": [
                    ("voir_auteur", "Peut voir un auteur"),
                    ("changer_auteur", "Peut modifier un auteur"),
                    ("supp_auteur", "Peut supprimer un auteur"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="livre",
            options={
                "permissions": [
                    ("voir_livre", "Peut voir un livre"),
                    ("changer_livre", "Peut modifier un livre"),
                    ("supp_livre", "Peut supprimer un livre"),
                ]
            },
        ),
    ]
